apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx
spec:
  generators:
  - list:
      elements:
      - cluster: engg-prod
        url: https://vc-yukged153oth7xpngwko.apps.aws-mumbai-eks.klusternetes.com
      - cluster: in-cluster
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-nginx'
    spec:
      project: default
      source:
        repoURL: https://charts.bitnami.com/bitnami
        chart: nginx
        targetRevision: 9.7.5
        helm:
          releaseName: nginx
      destination:
        server: '{{url}}'
        namespace: default
