apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: default
spec:
  encryptedData:
    password: AgBdf6W99MOZ8v5Wdz3MUSQJSHgAOmF4XEOVBiYaQnf7rwS5do1RoAwVbyIU4L4jS1wIWJxNTCb6nTqdUm02IkV5wwvM4qdY8g5pFxhZftN3qjNNhQdA5yeSRW4SMQSXKFPp+uBrNZyWl4gy5l0cas5mwFfatg7frplfqe4ue9YiDhfXGE9CrZE+3CF31J5Y/8x1jCgpssJdlyIsVF15Iq09zhv5SB+xAxcpLt/jTtO0z/bl2oqJOc/C0T+DSe5yjvwNJ+DN6o/O+ua8bmhB4qSePMPbznpIAU0xoeyawqbC+FF3Phm1WstojVaIjKRLoNnxJaa0eCGxTjcwLMx+Nxk9INhq8peFVY5AGDDymP3oSW1PDCAPziydjQP6mowjh8+ntiHeJkjrFVDSP+6Fs/A39+t6JOcqJTYzArqtUwGPH2U9sVAtnkzB9VPSnsGT0MKg5pRVIr90lFmK/ZBhOKFKKTiH93J7RYvNWDtlwvC9KmfIljRhu8Co49tR+oJ9OnZrRZ68ym45/qVj7XYlnY1Y1wN4HwwxIKJDpU8tA3vPR/piFTnmbMMcWdBLhCaYfjYE1RkI6LqMXtrdn8Zxia5AAiGvCaXzafa9Q+aDCWba99gypCNLvyRoPxygZ/T1viGQUtXvLziO36qiDAbNrjwqYpWI+mWc1tSoqRke1QAMSVUfhInQ5Lb7N6TzSB1ADb0=
    user: AgCf6GU0wW5VfzGkrQ6BahOc7NdA6iYoLRF+uIEqmgDr0RIJRY3NT6vHCCnCMDZ2835ospJ7NrkVtgwVJsNXrIbzguIgLOxqoMpOfzkP6OKy9pYJa7yWuhYTbIrv2Uhi8lgcbC80R27rYLivyQlIXfSzrDtJoR+OwZDwo0Zsjq5yYJkEldlSjAqzyoQL/7HV5LuojxbABi6ESxJLUyOWO8WYjwmf1eW3AmKY1Cv6vQrAQgiA2tlSPILCkhuAg+SF6+X4cKpfZWgnbpUZsmSdSUl3sRaxYCsJwoHT2hKh+mAUi07AdfVa8hF5zdXJVBzRZynYRqLKPF5v8D82enxsw6QwUSHsZviAs07ON+xU8cUWKYvBQtl9n7G/ekCYP3mHAfCwWiRjnXkuieJJwvOdJq0tMJHvNFdmlrz0+gNYpyv7hcyWUFjpg51l7Ebu0kOqJqEN11c2R9ZgWalMEprzuwTUxj5sI1+y962J0Fuw3uGRpn6byoXjtKURKvbbQN6p5eS8F5ap6qyg5BBffXDsOhQ6Om8H98jOMYMi08SpquZx336L/luipOFTMAPCl41J9hPGjSyUTzuchJaoeQ8iQyb2b6+IrJQ8n7FrhpSDJifqok2gutXIix0l7LdiFrRpcf9XFG7kgwH93A7DxL6B487ZRThM7NQbH8nepG59S53Rn3iAJoajM4c+qB8r9ksyL6Yvj/Z5/JyXNA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: default
